### PR TITLE
Use associated function syntax for `Debug` and `Display` backtrace impl

### PR DESCRIPTION
**Pull request by azriel91**
Rust 1.31 reports a compilation error saying it is ambiguous which
`fmt` method to call.

---

Not sure if this happened prior to Rust 1.31, but when compiling `failure` using Rust 1.31.0 (stable) this error shows up:

```rust
[07:33:30] failure master
$ cargo +stable test --all
...
error[E0034]: multiple applicable items in scope
   --> src\backtrace\mod.rs:132:20
    |
132 |                 bt.fmt(f)
    |                    ^^^ multiple `fmt` found
    |
    = note: candidate #1 is defined in an impl of the trait `std::fmt::Debug` for the type `backtrace::backtrace::Backtrace`
    = note: candidate #2 is defined in an impl of the trait `std::fmt::Display` for the type `backtrace::backtrace::Backtrace`

error[E0034]: multiple applicable items in scope
   --> src\backtrace\mod.rs:140:20
    |
140 |                 bt.fmt(f)
    |                    ^^^ multiple `fmt` found
    |
    = note: candidate #1 is defined in an impl of the trait `std::fmt::Debug` for the type `backtrace::backtrace::Backtrace`
    = note: candidate #2 is defined in an impl of the trait `std::fmt::Display` for the type `backtrace::backtrace::Backtrace`

error: aborting due to 2 previous errors
```

### CODE REVIEW

**Comment by BurntSushi** [comment]
I don't think this is caused by Rust 1.31. `failure` on master doesn't compile on Rust 1.30 either. My _guess_ is that [this PR in `backtrace` which was just recently merged](https://github.com/alexcrichton/backtrace-rs/commit/f881a82ad85f27a16473d92ed05deb9380a879b6#diff-896f84842ee1b6527b2fe1161ca5f8a0R275) is the instigator, which I guess made which impl to select ambiguous? Interesting.

**Comment by azriel91** [comment]
Ah, I did recently run `cargo update` in the other project that used this. A *very subtle* breaking change 👻.

**Comment by BurntSushi** [comment]
Indeed. My suspicion is that adding an impl like `Backtrace` did is within the realm of "acceptable" breakage, but yeah, I'm not sure how one anticipates something like this.

cc @alexcrichton

**Comment by mpapierski** [comment]
That was fast. Thanks! Looking forward for `failure v0.1.4`.

**Comment by alexcrichton** [comment]
I just boarded a plane and can't deal with this for an hour, I will yank the current version and we can figure how how to add the relevant impl to the backtrace crate later

**Comment by mpapierski** [comment]
@alexcrichton That sounds great. Do you mean yank backtrace 0.3.10?

For anyone still puzzled there is temporary workaround:

```sh
cargo update -p backtrace --precise 0.3.9 
```

**Comment by alexcrichton** [comment]
Apologies for the breakage here!

For posterity, the root cause was that backtrace 0.3.10 was just published and added `Display for Backtrace`. This in turn causes the method resolution error in this crate which wanted the `Debug` implementation.

I deleted `Display for Backtrace`, published 0.3.11, and yanked 0.3.10. I'll hold off on re-adding `Display` until a later date, but landing this in the meantime would likely be good regardless!

**Comment by RalfJung** [comment]
What's up with CI for this PR? In [my PR doing the same thing](https://github.com/rust-lang-nursery/failure/pull/282), CI failed because backtrace seems to be no longer compatible with Rust 1.18.

File: src/backtrace/mod.rs [hunk 1]
```diff
@@ -129,15 +129,15 @@ with_backtrace! {
...
+                Debug::fmt(bt, f)
             } else { Ok(()) }
         }
     }
 
     impl Display for Backtrace {
         fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
             if let Some(bt) = self.internal.as_backtrace() {
-                bt.fmt(f)
+                Display::fmt(bt, f)
```
Comment (RalfJung) [inline src/backtrace/mod.rs]: This will not work with old versions of backtrace.  This should be `Debug::`, or the minimal version in `Cargo.toml` should be raised.

**Comment by azriel91** [comment]
@RalfJung, @BurntSushi: Since `backtrace` requires a higher Rust version, what should happen next?

* Raise the minimum Rust version for `failure`
* Make `backtrace` Rust 1.18 compatible
* Cap the version of `backtrace` in `failure`

**Comment by azriel91** [comment]
Option 3: https://github.com/alexcrichton/backtrace-rs/pull/137

File: Cargo.toml [hunk 2]
```diff
@@ -15,7 +15,7 @@ path = "./failure_derive"
 
 [dependencies.backtrace]
 optional = true
-version = "0.3.3"
+version = "0.3.11"
```
[the remark this answers is not in the document]
Comment (azriel91) [reply Cargo.toml]: oh true, fixed 🙇!

[the remark this answers is not in the document]
Comment (azriel91) [reply Cargo.toml]: Oh, there is a reason to lock down the version though, because the newer version is not Rust 1.18 compatible

**Comment by azriel91** [comment]
Pinned `backtrace` to `0.3.9` temporarily, pending https://github.com/alexcrichton/backtrace-rs/pull/137 (and release) before it is Rust 1.18.0 compatible.

Feel free to push over the branch if there's something urgent; I'm off for the night.

**Comment by azriel91** [comment]
Backtrace 0.3.13 hasn't yet been released, but its minimum supported Rust version is increased to 1.25.0, so I did that here as well.
