### ISSUE TITLE
Error enum doesn't implement 'std::fmt::Display'

### ISSUE THREAD

**Issue by AxelMontini** [rust-lang-nursery/failure#226]
I can't use this crate, as even the minimal example found in the README doesn't work.

I'm including the git repo as dependency in the manifest.

*Edit*: problem only present on version 1.0; version 0.1 works fine.
## Code
```
#[macro_use]
extern crate failure;

#[derive(Debug, Fail)]
pub enum ToolchainError {
    #[fail(display = "invalid toolchain name: {}", name)]
    InvalidToolchainName {
        name: String,
    },
    #[fail(display = "unknown toolchain version: {}", version)]
    UnknownToolchainVersion {
        version: String,
    }
}
```
## Error
```
error[E0277]: `ToolchainError` doesn't implement `std::fmt::Display`
  --> src/lib.rs:14:17
   |
14 | #[derive(Debug, Fail)]
   |                 ^^^^ `ToolchainError` cannot be formatted with the default formatter
   |
   = help: the trait `std::fmt::Display` is not implemented for `ToolchainError`
   = note: in format strings you may be able to use `{:?}` (or {:#?} for pretty-print) instead
```
## Expand
Looking at the generated code with cargo-expand I see no implementation of std::fmt::Display.

**Comment by AxelMontini** [comment]
The README doesn't explicitly say that the syntax in the example is outdated and only valid for version 0.1 of failure.

**Comment by ufoscout** [comment]
@AxelMontini 
could you please provide the steps you applied to solve this issue?

**Comment by AxelMontini** [comment]
@ufoscout 
As I said I was using version 1.0 and by looking at the source code I discovered that:
1) I had to derive Display for my type
2) Change the syntax from `#[fail(display = "my formatted message")]` to `#[display(fmt = "my formatted message")]`
These steps made my program compile and work with version 1.0 of this crate.
As an alternative you can use version 0.1 and the old syntax.

I hope I haven't forgotten anything.

**Comment by ufoscout** [comment]
@AxelMontini 
ok, thanks, I solved using `#[fail(display = "my formatted message")]`.
Anyway, was version 1.0 already released? I see only 0.1.1 in crates.io

**Comment by AxelMontini** [comment]
@ufoscout 
It wasn't released, but you can use it from this git repo. Just set the dependency to `failure = {git = "https://github.com/rust-lang-nursery/failure", version = "1.0"}` to use it.
