### PR TITLE
Allow failures on nightly because it's not always stable

### PR DESCRIPTION
**Pull request by palfrey**
This fixes the build failure seen in https://github.com/rust-lang-nursery/failure/pull/300 (and will probably show up in master if it got rebuilt again now)

### CODE REVIEW

**Comment by BurntSushi** [comment]
I don't agree with this. Nightly isn't failing because it's "not stable," but rather, because this crate lifts all warnings to compilation errors when running tests, and this crate is now using the deprecated `&Trait` syntax instead of the `&dyn Trait` syntax.

If we want to still maintain the same MSRV, then we should just address the warnings individually. e.g., `#![allow(bare_trait_objects)]` is what I've done in a few of my crates.

**Comment by palfrey** [comment]
I've added the "allow" at the top level of the lib, which should fix the nightly builds. I still think that nightly should be marked as "allow fail" as changes to nightly shouldn't break builds (as it is occasionally actually unstable).

**Comment by palfrey** [comment]
@davidbarsky Any chance of getting this merged as I think this will fix the current build issues?

**Comment by davidbarsky** [comment]
@palfrey Apologies for the delay, Tom. I think failure 0.1.6 ought resolve theses issues. Can you let me know if you're still seeing them?

**Comment by palfrey** [comment]
I think 996f919f1e1741b08673b15f893221694097cc9f resolves this. #300's build should be rerun as it should now work, but everything else seems good to me
