### PR TITLE
use public TokenStream instead of private

### LINKED ISSUE #342: failure_derive won't build with quote 1.0.3
My CI builds just started failing with the following error:

```
error[E0433]: failed to resolve: could not find `__rt` in `quote`
   --> /Users/sloveless/.cargo/registry/src/github.com-1ecc6299db9ec823/failure_derive-0.1.6/src/lib.rs:107:70
    |
107 | fn display_body(s: &synstructure::Structure) -> Result<Option<quote::__rt::TokenStream>, Error> {
    |                                                                      ^^^^ could not find `__rt` in `quote`
```

Looks like the `quote` crate renamed `__rt` to `__private` in its `1.0.3` release that just came out: https://github.com/dtolnay/quote/commit/41543890aa76f4f8046fffac536b9445275aab26

### PR DESCRIPTION
**Pull request by grokse**
attempts to fix #342

### CODE REVIEW

**Comment by normano** [comment]
@davidbarsky
