### ISSUE TITLE
compile broken by newest version of backtrace crate (0.3.10)

### ISSUE THREAD

**Issue by lavifb** [rust-lang-nursery/failure#280]
failure crate will no longer compile with backtrace 0.3.10

It seems to have to do with some new added definition for fmt

>    Compiling failure v0.1.3 
> error[E0034]: multiple applicable items in scope
>    --> src/backtrace/mod.rs:132:20
>     |
> 132 |                 bt.fmt(f)
>     |                    ^^^ multiple `fmt` found
>     |
>     = note: candidate #1 is defined in an impl of the trait `std::fmt::Debug` for the type `backtrace::backtrace::Backtrace`
>     = note: candidate #2 is defined in an impl of the trait `std::fmt::Display` for the type `backtrace::backtrace::Backtrace`
> 
> error[E0034]: multiple applicable items in scope
>    --> src/backtrace/mod.rs:140:20
>     |
> 140 |                 bt.fmt(f)
>     |                    ^^^ multiple `fmt` found
>     |
>     = note: candidate #1 is defined in an impl of the trait `std::fmt::Debug` for the type `backtrace::backtrace::Backtrace`
>     = note: candidate #2 is defined in an impl of the trait `std::fmt::Display` for the type `backtrace::backtrace::Backtrace`
> 
> error: aborting due to 2 previous errors
> 
> For more information about this error, try `rustc --explain E0034`.
> error: Could not compile `failure`.
> 
> To learn more, run the command again with --verbose.
>

**Comment by BurntSushi** [comment]
See also https://github.com/rust-lang-nursery/failure/pull/279

**Comment by lavifb** [comment]
Oh nice. It looked like something small like that. 

I'll close this issue then.
